name: Apps CI/CD

on:
  # Trigger workflow on Friday at 1.00 AM UTC
  #schedule:
  #   - cron: '0 1 * * 5'
  push:
    branches: 
      - main
  pull_request:
    types: [pull]
    branches:
      - main

jobs:
  test:
    name: "Test site using Playwright"
    runs-on: ubuntu-latest 
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: npm setup
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          check-latest: true
      - name: Install dependencies
        run: | 
          npm i
      - name: Intalling playwright
        run: |
          npx playwright install
      - name: Run Playwright Tests      
        run: |   
          npx playwright test --reporter=html
